README.md
docs/code.rst
docs/issues.rst
docs/peer.rst
docs/userguide.rst
repomate/cli.py
repomate/command.py
repomate/github_api.py
repomate/tuples.py
repomate/util.py
tests/test_command.py
tests/test_github_api.py
tests/test_util.py

Adds the `assign-peer-reviewers` and `purge-peer-review-teams` commands.

Add peer review

---

.travis.yml
docs/clone.rst
docs/configuration.rst
docs/getting_started.rst
docs/index.rst
docs/issues.rst
docs/peer.rst
docs/update.rst
repomate/cli.py
repomate/command.py
repomate/config.py
repomate/main.py
repomate/plugin.py
tests/conftest.py
tests/test_config.py

Add the show-config command and update the documentation accordingly.

Show config

---

.travis.yml
.travis/install.sh
.travis/run.sh
tox.ini

Run maxOS builds with tox

---

.travis.yml

Limit builds to master and release tags

---

README.md
docs/peer.rst
docs/plugins.rst
repomate/cli.py
repomate/tuples.py
tests/test_cli.py

Deprecate review commands

---

repomate/cli.py
tests/test_cli.py

Fix #149 
Also fixes the root cause of #134

Only allow https for the base url

---

README.md
docs/fundamentals.rst

General updates to documentation to keep it in phase with new developments.
Fix #170

[docs] Update out-of-date documentation

---

tox.ini

Make tox install non-editable

---

repobee/cli.py
repobee/command.py
repobee/git.py
repobee/github_api.py
tests/test_cli.py
tests/test_command.py
tests/test_exception.py
tests/test_git.py
tests/test_github_api.py

This turned into a fairly large refactor. There are a few hacks in there that can only be resolved by breaking changes (see #184), so that will have to wait until 2.0.
Fix #180

Improve authentication

---

repobee/cli.py

Deprecate --mu/--master-repo-urls argument for migrate command

---

docs/getting_started.rst
docs/migrate.rst
repobee/cli.py
repobee/command.py
tests/test_command.py

Stop adding migrated repos to the `master_repos` team

---

repobee/github_api.py
tests/test_github_api.py

Fix #198 
Fix #197 (in the sense that the feature affected by the bug has been removed)

Fix crash in GitHubAPI.create_repos

---

repobee/github_api.py
tests/test_github_api.py

[fact] Adapt github_api.GitHubAPI to the apimeta.API class

---

repobee/cli.py
repobee/exception.py
repobee/github_api.py
tests/test_github_api.py

[fact] Replace exception.GitHubError with exception.APIError

---

repobee/cli.py
repobee/command.py
repobee/gitlab_api.py
requirements.txt
setup.py
tests/test_cli.py
tests/test_gitlab_api.py

Add the `gitlab_api` module, which features core support for GitLab.
Fix #188

[feat] Add core support for GitLab

---

repobee/gitlab_api.py
tests/test_gitlab_api.py

Fix org_name argument being ignored

---

repobee/apimeta.py
repobee/command.py
repobee/github_api.py
repobee/gitlab_api.py
repobee/tuples.py
repobee/util.py
tests/constants.py
tests/functions.py
tests/test_cli.py
tests/test_command.py
tests/test_github_api.py
tests/test_gitlab_api.py

[fact] Wrap Repo, Issue and Team API objects in apimeta

---

repobee/apimeta.py
repobee/cli.py
repobee/command.py
repobee/github_api.py
repobee/gitlab_api.py
repobee/tuples.py
tests/constants.py
tests/test_cli.py
tests/test_command.py
tests/test_gitlab_api.py

[fact] Replace tuples.Group with apimeta.Team

---

repobee/apimeta.py
repobee/command.py
repobee/github_api.py
repobee/gitlab_api.py
tests/test_command.py
tests/test_github_api.py
tests/test_gitlab_api.py

This PR does a bit too much, but eh.
Fix #212  
Fix #213 
Fix #215

[fact] Refactor APISpec

---

tests/plugin_tests/test_defaults.py
tests/plugin_tests/test_pairwise.py
tests/test_cli.py
tests/test_github_api.py

[misc] Call all outside of assert

---

repobee/command.py
tests/test_command.py

[fix] Fix incorrect kwargs used in calls to get_repo_urls

---

README.md
docs/fundamentals.rst
docs/gitlab.rst
docs/userguide.rst

[docs] Document gitlab usage

---

repobee/command.py
tests/test_command.py

[fact] Update docstrings/type hints in command module

---

repobee/apimeta.py
tests/test_apimeta.py

[fact] Disallow access to None APIObject implementation attr

---

.gitignore
.travis/integration_test.sh
repobee/gitlab_api.py
tests/integration_tests/integration_tests.py

Fixes the `migrate` command for GitLab
Fix #226

[fix] Fix migrate command for GitLab

---

Dockerfile.test
repobee/gitlab_api.py
tests/integration_tests/integration_tests.py

Test coverage will go down, because the added system test is not measured. Can't be helped atm.
Fix #243

[feat] Enable open-issues command for the GitLabAPI

---

repobee/gitlab_api.py
tests/integration_tests/integration_tests.py

This automatically enables the `close-issues` command for use with GitLab.
Again, coverage will drop as this is only system tested, and the system tests are not coverage measured.
Fix #244

[feat] Implement GitLabAPI.close_issue

---

tests/unit_tests/plugin_tests/test_defaults.py
tests/unit_tests/test_apimeta.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_command.py
tests/unit_tests/test_config.py
tests/unit_tests/test_git.py
tests/unit_tests/test_github_api.py
tests/unit_tests/test_plugin.py
tests/unit_tests/test_util.py

[fix] Fix usage of pytest's ExceptionInfo

---

repobee/command.py
tests/unit_tests/test_command.py

[fix] Fix accessing non-existing attribute on apimeta.Issue

---

repobee/gitlab_api.py
tests/integration_tests/integration_tests.py

Implements the `GitLabAPI.get_issues` method, wich in turn enables `list-issues` for GitLab.
Fix #245

[feat] Enable list-issues command for GitLabAPI

---

repobee/gitlab_api.py
tests/unit_tests/test_gitlab_api.py

[fix] Correctly decode TeamPermission in GitLabAPI

---

docs/gitlab.rst

Update the GitLab-related documentation for v1.6.0
Fix #241 
Fix #248 
Fix #262

[docs] Update GitLab docs

---

repobee/cli.py
repobee/config.py
repobee/tuples.py
tests/integration_tests/integration_tests.py
tests/unit_tests/conftest.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_config.py
tests/unit_tests/test_main.py

[feat] Rename github-base-url argument to base-url

---

repobee/cli.py

[docs] Update cli docstrings/annotations/help sections

---

repobee/cli.py
repobee/command.py
repobee/config.py
repobee/ext/defaults.py
repobee/ext/github.py
repobee/ext/gitlab.py
repobee/ext/javac.py
repobee/ext/pylint.py
repobee/formatters.py
repobee/git.py
repobee/main.py
repobee/tuples.py
tests/unit_tests/plugin_tests/test_github.py

For a better user experience
Fix #270

[feat] Capitalize the first letter of every log message

---

repobee/cli.py
repobee/ext/github.py
tests/integration_tests/integration_tests.py
tests/unit_tests/plugin_tests/test_github.py
tests/unit_tests/test_cli.py

[feat] Add user to base args

---

tests/integration_tests/integration_tests.py

[fact] Refactor integration tests

---

tests/integration_tests/integration_tests.py

Add a couple of happy-path system tests for the clone command.
Fix #239

[misc] Add system tests for clone command

---

src/_repobee/command.py

Some minor bugs related to peer review command.
Fix #302 
Related to #303

[fix] Fix peer review bugs

---

src/_repobee/cli.py
tests/integration_tests/integration_tests.py
tests/unit_tests/conftest.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_main.py

[feat] Make CLI options GNU/POSIX compatible

---

src/_repobee/cli.py
tests/unit_tests/test_cli.py

[feat] Remove deprecated peer review commands

---

src/_repobee/cli.py
src/_repobee/command.py
src/_repobee/ext/github.py
src/_repobee/formatters.py
tests/unit_tests/plugin_tests/test_github.py
tests/unit_tests/test_command.py

[feat] Implement peer review for groups

---

requirements.txt
setup.py
src/_repobee/cli.py
src/_repobee/command.py
tests/unit_tests/test_cli.py

[feat] Add --hook-results-file option to list-issues command

---

requirements.txt
setup.py
src/_repobee/cli.py
tests/unit_tests/test_cli.py

[feat] Add possibility for ext commands to request base parsers

---

requirements.txt
setup.py
src/_repobee/command.py
src/_repobee/ext/github.py
src/_repobee/ext/gitlab.py
src/_repobee/util.py
tests/integration_tests/integration_tests.py
tests/unit_tests/plugin_tests/test_github.py
tests/unit_tests/plugin_tests/test_gitlab.py
tests/unit_tests/test_command.py

[fact] Move name generation functions to repobee-plug

---

src/_repobee/cli.py
src/_repobee/config.py
tests/unit_tests/test_config.py

[fact] Move token env variable parsing to config module

---

src/_repobee/ext/gitlab.py
tests/unit_tests/plugin_tests/test_gitlab.py

[fact] Wrap python-gitlab exceptions in RepoBee exceptions

---

CONTRIBUTING.md
docs/contributing.rst
docs/index.rst

[docs] Add development environment setup guide

---

docs/gitlab.rst
src/_repobee/cli.py
src/_repobee/ext/gitlab.py
tests/unit_tests/plugin_tests/test_gitlab.py

[feat] Add GitLab compatibility for verify-settings command

---

src/_repobee/ext/gitlab.py
tests/integration_tests/integration_tests.py
tests/unit_tests/plugin_tests/test_gitlab.py

Fix #345 
Code coverage will drop as I still haven't figured out #350

[feat] Add GitLab compatibility for assign-reviews command

---

src/_repobee/ext/gitlab.py
tests/integration_tests/integration_tests.py
tests/unit_tests/plugin_tests/test_gitlab.py

[feat] Add GitLab compatibility for end-reviews command

---

requirements/app.txt
setup.py
src/_repobee/ext/gitlab.py
tests/integration_tests/integration_tests.py

[fix] Parse raw created_at attribute in GitLabAPI to datetime.datetime

---

src/_repobee/ext/gitlab.py
tests/integration_tests/integration_tests.py

Fix #347 
Implement GitLabAPI.get_review_progress and add some integration tests for it.
Again, coverage will decrease as #350 remains unsolved and there are only integration tests for this.

[feat] Add GitLab compatibility for check-reviews command

---

src/_repobee/ext/gitlab.py
tests/integration_tests/integration_tests.py

Fix #361 
Now exits early instead with a message of what repos are missing.

[fix] Fix KeyError when student repo is missing in assign-reviews (GitLab)

---

src/_repobee/ext/github.py
tests/unit_tests/plugin_tests/test_github.py

[feat] Add check on the base url in GitHubAPI

---

.travis.yml
.travis/integration_test.sh
.travis/upload_coverage.sh
Dockerfile.test
tests/integration_tests/integration_tests.py

Finally found a working solution to running the integration tests with coverage. It's a bit messy, but it works!
Fix #350

[misc] Measure coverage on integration tests

---

.travis.yml
.travis/install.sh
.travis/run.sh

[misc] Run macOS build without caching and only on Python 3.5.4

---

src/_repobee/exception.py
src/_repobee/ext/gitlab.py
tests/unit_tests/plugin_tests/test_gitlab.py

[fix] Make GitLabAPI throw NotFoundError on not finding group

---

.readthedocs.yml
requirements/docs.txt

[docs] Fix RTD config

---

docs/contributing.rst

Fix missing code bloc in docs

---

src/_repobee/cli/dispatch.py
src/_repobee/cli/mainparser.py
src/_repobee/cli/parsing.py
src/_repobee/cli/preparser.py
src/_repobee/command/repos.py
src/_repobee/config.py
src/_repobee/main.py
src/_repobee/plugin.py
tests/unit_tests/conftest.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_command.py
tests/unit_tests/test_config.py
tests/unit_tests/test_main.py

[feat] Add --config preparser option

---

src/_repobee/command/repos.py
src/_repobee/ext/javac.py
src/_repobee/plugin.py
tests/unit_tests/test_plugin.py

[misc] Remove calls to act_on_cloned_repo hook

---

src/_repobee/main.py
src/_repobee/plugin.py
src/repobee.py
tests/unit_tests/repobee/conftest.py
tests/unit_tests/repobee/test_command.py
tests/unit_tests/repobee/test_plugin.py

[feat] Expose functionality for testing plugins in repobee module

---

docs/conf.py
docs/index.rst
docs/install.rst
docs/plugins.rst
docs/repobee_plug/creating_plugins.rst
docs/repobee_plug/index.rst
docs/repobee_plug/overview.rst

Update refs in documentation to reflect bundling of repobee-plug

---

src/_repobee/plugin.py

[fact] Refactor try_register_plugin

---

CONTRIBUTING.md

[docs] Improve description of PR conventions

---

.github/workflows/static-analysis.yml
requirements/test.txt
setup.py
src/_repobee/plugin.py

Fix #461
This PR adds a GitHub action that runs flake8 (style checks) and bandit (security checks).

[test] Add static analysis GitHub action

---

.github/workflows/static-analysis.yml
requirements/test.txt
setup.py

[test] Add black --check to CI

---

src/_repobee/cli/parsing.py

[feat] Set logfile logging level to DEBUG

---

src/_repobee/ext/gitlab.py

#460
In [gitlab module](https://github.com/repobee/repobee/blob/master/src/_repobee/ext/gitlab.py)

[fact] Replace str.format with f-strings in GitLab module

---

docs/getting_started.rst
src/_repobee/constants.py
tests/unit_tests/repobee/conftest.py

[break] Replace .cnf config file suffix with .ini

---

src/_repobee/ext/defaults/configwizard.py
src/repobee_plug/_pluginmeta.py
src/repobee_plug/cli.py
tests/unit_tests/repobee_plug/test_pluginmeta.py

[fact] Rename command_callback to command

---

src/_repobee/main.py
tests/unit_tests/repobee/test_main.py

[feat] Add workdir argument to repobee.run

---

docs/configuration.rst
docs/getting_started.rst
docs/plugins.rst
src/_repobee/config.py
src/_repobee/constants.py
src/_repobee/ext/defaults/configwizard.py
tests/integration_tests/README.md
tests/unit_tests/repobee/conftest.py
tests/unit_tests/repobee/plugin_tests/test_configwizard.py
tests/unit_tests/repobee/test_config.py
tests/unit_tests/repobee/test_main.py
tests/unit_tests/repobee_plug/test_pluginmeta.py

[break] Rename DEFAULTS header to repobee

---

src/_repobee/cli/parsing.py
src/_repobee/exception.py
src/_repobee/ext/defaults/github.py
src/_repobee/ext/gitlab.py
src/repobee_plug/__init__.py
src/repobee_plug/_apimeta.py
src/repobee_plug/_exceptions.py
tests/unit_tests/repobee/plugin_tests/test_github.py
tests/unit_tests/repobee/plugin_tests/test_gitlab.py
tests/unit_tests/repobee/test_cli.py

[fact] Move APIError and suberrors to plug

---

tests/integration_tests/docker-compose.yml

Fix #534 
Here we go again ...

[test] Fix flaky integration tests

---

src/_repobee/cli/dispatch.py
src/_repobee/cli/mainparser.py
src/_repobee/cli/parsing.py
src/_repobee/command/issues.py
src/_repobee/command/peer.py
src/_repobee/command/repos.py
src/_repobee/config.py
src/_repobee/ext/defaults/configwizard.py
src/_repobee/ext/defaults/github.py
src/_repobee/ext/gitlab.py
src/_repobee/ext/pairwise.py
src/_repobee/ext/pylint.py
src/_repobee/ext/query.py
src/_repobee/formatters.py
src/_repobee/git.py
src/_repobee/main.py
src/_repobee/plugin.py
src/repobee_plug/_containers.py
src/repobee_plug/_pluginmeta.py
src/repobee_plug/log.py
tests/unit_tests/repobee/plugin_tests/test_gitlab.py
tests/unit_tests/repobee/test_main.py
tests/unit_tests/repobee/test_plugin.py

This is a partial solution to #546. It centralizes logging, but now there's little to no user feedback. So that needs to be added.

[fact] Replace individual file loggers with centralized logging facilities

---

requirements/app.txt
setup.py
src/_repobee/cli/dispatch.py
src/_repobee/cli/parsing.py
src/_repobee/command/__init__.py
src/_repobee/command/issues.py
src/_repobee/command/peer.py
src/_repobee/command/progresswrappers.py
src/_repobee/command/repos.py
src/_repobee/command/teams.py
src/_repobee/ext/defaults/configwizard.py
src/_repobee/ext/defaults/github.py
src/_repobee/ext/gitlab.py
src/_repobee/ext/pylint.py
src/_repobee/ext/query.py
src/_repobee/git.py
src/_repobee/main.py
src/repobee_plug/__init__.py
src/repobee_plug/_apimeta.py
src/repobee_plug/cli/io.py
tests/integration_tests/integration_tests.py

Fix #546 
Also fix #548 
Adds much nicer user feedback in the form of progress bars.

[feat] Revamp user feedback

---

src/repobee_plug/_apimeta.py

[fact] Refactor API objects into proper dataclasses

---

src/_repobee/ext/defaults/github.py
tests/unit_tests/repobee/plugin_tests/test_github.py

[fix] Fix GitHubAPI issue bugs

---

.github/workflows/static-analysis.yml
requirements/test.txt
setup.py
src/_repobee/command/__init__.py
src/_repobee/command/issues.py
src/_repobee/command/peer.py
src/_repobee/command/repos.py
src/_repobee/disthelpers.py
src/repobee_plug/_deprecation.py
src/repobee_plug/cli/__init__.py
src/repobee_plug/cli/categorization.py
src/repobee_plug/cli/commandmarkers.py
src/repobee_plug/cli/settings.py

[fact] Add pylint to CI and fix related linting issues

---

src/_repobee/cli/dispatch.py
src/_repobee/cli/mainparser.py
src/repobee_plug/cli/_corecommand.py
tests/unit_tests/repobee/test_cli.py

[fact] Move create-teams command into its own teams category

---

src/_repobee/plugin.py
tests/new_integration_tests/test_repos.py

Fix #575 
The fix is minimal, the real contribution here is the two tests.

[fix] Fix broken calls to post_clone and pre_setup hooks

---

src/_repobee/disthelpers.py
src/_repobee/ext/dist/pluginmanager.py
tests/new_integration_tests/test_dist.py

[fix] Add safeguard against accidental downgrading

---

tests/new_integration_tests/test_dist.py

[test] Fix flaky downgrade safeguard test

---

src/_repobee/ext/dist/pluginmanager.py
tests/new_integration_tests/test_dist.py

[fix] Fix crash in `plugin uninstall` command

---

src/_repobee/cli/dispatch.py
src/repobee_testhelpers/funcs.py

Fix #613 
Also adds integration tests for `teams create`, as well as a progress bar to the CLI for user feedback (YAY, PROGRESS BARS).

[fix] Make `teams create` actually do something

---

src/_repobee/disthelpers.py
src/_repobee/ext/dist/distmanager.py
tests/new_integration_tests/test_dist.py

[fix] Make `manage upgrade` activate dist plugins

---

src/_repobee/ext/dist/pluginmanager.py
tests/new_integration_tests/test_dist.py

Fix #617 
This PR adds editable installation of local plugin packages. Good for development purposes, and can be used to install unofficial plugins.

[feat] Allow installation of local plugin packages

---

scripts/install.sh

[fix] Have install script look for more python executables

---

src/_repobee/ext/javac.py
tests/new_integration_tests/test_repos.py

[fix] Fix crash in javac plugin when ignore list is None

---

src/_repobee/ext/pylint.py
tests/new_integration_tests/test_repos.py

[fix] Fix the broken pylint plugin

---

src/_repobee/git.py
tests/new_integration_tests/test_repos.py

[fix] Allow cloning of empty student repositories

---

tests/new_integration_tests/test_issues.py

Fix #620 
Adds two integration tests for the issues list command.

[test] Add new tests for the `issues list` command

---

src/_repobee/command/repos.py
tests/new_integration_tests/test_config_category.py

[fix] Fix missing newline bug in `config show`

---

tests/new_integration_tests/test_repos.py

[test] Add push rejected test for `repos update`

---

.github/workflows/static-analysis.yml
requirements/app.txt
src/_repobee/cli/argparse_ext.py
src/_repobee/cli/dispatch.py
src/_repobee/cli/parsing.py
src/_repobee/cli/preparser.py
src/_repobee/command/issues.py
src/_repobee/command/peer.py
src/_repobee/command/repos.py
src/_repobee/constants.py
src/_repobee/disthelpers.py
src/_repobee/ext/defaults/configwizard.py
src/_repobee/ext/defaults/github.py
src/_repobee/ext/dist/pluginmanager.py
src/_repobee/ext/gitlab.py
src/_repobee/ext/javac.py
src/_repobee/ext/pairwise.py
src/_repobee/formatters.py
src/_repobee/git.py
src/_repobee/plugin.py
src/repobee_plug/__init__.py
src/repobee_plug/_pluginmeta.py
src/repobee_plug/localreps.py
src/repobee_plug/name.py
src/repobee_plug/platform.py
src/repobee_plug/types.py
src/repobee_testhelpers/funcs.py
src/repobee_testhelpers/localapi.py
tests/unit_tests/repobee_plug/test_pluginmeta.py

Fix #468 
All of RepoBee is now linted with MyPy. Which is nice. This PR's major contribution is fixing all type hint inconsistencies and errors, of which there were a ton.

[misc] Lint entire project with MyPy

---

.travis.yml

Fix #685 
The system tests are too slow to always execute.

[test] Run system tests only for tags

---

docs/issues.rst

[docs] Update mention of list-issues to `issues list`

---

docs/faq.rst
docs/index.rst
scripts/install.sh
src/_repobee/main.py
tests/unit_tests/repobee/test_main.py

Fix #677 
Also adds links to the FAQ in error messages.

[docs] Add FAQ

---

src/_repobee/main.py
tests/unit_tests/repobee/test_main.py

[fix] Fix "unexpected exit" error being logged on user error

---

docs/plugins.rst

[docs] Update docs on general usage of plugins

---

.travis.yml

[test] Actually run cron job on master

---

.github/workflows/static-analysis.yml
.github/workflows/tests.yml

[test] Add GitHub Action cron jobs

---

docs/_ext/generate_package_docs.py
src/_repobee/ext/tamanager.py

[docs] Document usage of the tamanager plugin

---

.github/workflows/tests.yml

[test] Add Python 3.9 to GitHub Action tests (Linux only)

---

.github/workflows/static-analysis.yml
src/_repobee/ext/defaults/github.py

[fix] Wrap unwrapped GitHub API calls in try

---

src/_repobee/cli/parsing.py
tests/new_integration_tests/test_plugins.py

[fix] Fix discovery parser for plugins

---

src/repobee_plug/_pluginmeta.py
tests/new_integration_tests/test_plugins.py

[fix] Add early checks for discovery parser constraints

---

src/_repobee/ext/defaults/github.py
src/_repobee/ext/gitlab.py
tests/unit_tests/repobee/plugin_tests/test_github.py
tests/unit_tests/repobee/plugin_tests/test_gitlab.py

[feat] Weaken `config verify` to  warn when user is not owner

---

docs/fundamentals.rst
docs/getting_started.rst
docs/index.rst
docs/issues.rst
docs/repos.rst
docs/taquickstart.rst

Fix #725 
Also moves some stuff around in the docs for it to make more sense.

[docs] Add TA quickstart to docs

---

scripts/install.sh

#735 
This is a prerequisite for building versioned Docker containers.

[misc] Enable install script to install from local directory

---

docs/repobee_plug/creating_plugins.rst

[docs] Add section on using a virtual environment for plugin development

---

src/repobee_plug/_pluginmeta.py
tests/unit_tests/repobee_plug/test_pluginmeta.py

Fix #745 
Uses `shlex.split` to split configured arguments, and also applies the converter (if available) to each individual argument. This applies to arguments configured with `nargs="+"`, `nargs="*"` or `nargs=N`, where `N` is a positive integer.

[fix] Add support for configuring list-like arguments

---

src/_repobee/cli/mainparser.py
src/_repobee/git.py
tests/new_integration_tests/test_repos.py

[feat] Stash changes in student repos when cloning with --update-local

---

src/_repobee/command/repos.py
src/_repobee/git.py
tests/new_integration_tests/test_repos.py

Fix #733 
Sets `pull.ff=only` in student repos

[fix] Set pull.ff=only in student repos

---

src/_repobee/cli/argparse_ext.py
src/_repobee/cli/mainparser.py
src/_repobee/cli/pluginparsers.py
src/repobee_plug/cli/commandmarkers.py

This PR refactors the creation of plugin command parsers. It's in massive need of an overhaul.

[fact] Refactor creation of plugin command parsers

---

docs/faq.rst

[docs] Add better descriptions of how to fix bad config

---

docs/plugins.rst

Fix #759 
This is a general improvement of the docs on plugin activate/deactivation

[docs] Improve documentation of plugin activation/deactivation

---

README.md

[docs] Fix broken link in README

---

.github/workflows/deploy.yml

This PR adds a deploy workflow that triggers on a published release. It deploys RepoBee to PyPi.

[misc] Add deploy workflow

---

.github/workflows/tests.yml

Fix #780 
Just trying to get Codecov to post status updates again... Found this post: https://community.codecov.io/t/codecov-commit-status-check-missing-for-pr-when-using-codecov-action/1813

[test] Fix flaky Codecov status updates

---

src/_repobee/ext/defaults/github.py
src/_repobee/ext/gitlab.py

This PR improves the handling of URLs in the gitlab and github modules, making it a little bit safer and more structured.

[fact] Improve handling of URLs in github and gitlab modules

---

docs/plugins.rst

[docs] Document non-interactive management of plugins

---

src/_repobee/ext/gitea.py
system_tests/gitea/test_gitea.py

#732 
Implements `get_team_repos` and `get_repos` in the GiteaAPI

[feat] Implement get_team_repos and get_repos in GiteaAPI

---

src/_repobee/ext/gitea.py

#732 
Refactor of the GiteaAPI to do error handling in the requests wrapper function.

[fact] Simplify raising of errors on non-200 responses in GiteaAPI

---

src/_repobee/ext/gitea.py
system_tests/gitea/test_gitea.py

#782 
This PR adds the `get_repo_issues` and `create_issue` functions for the GiteaAPI.

[feat] Implement get_repo_issues and create_issue in GiteaAPI

---

src/_repobee/ext/gitea.py
system_tests/gitea/test_gitea.py

#732 
Adds the `delete_team` function to the GiteaAPI.

[feat] Implement GiteaAPI.delete_team

---

src/_repobee/plugin.py

Ignores a MyPy type error that surfaced in MyPy 0.790

[misc] Ignore MyPy type error

---

src/_repobee/cli/dispatch.py
src/_repobee/command/__init__.py
src/_repobee/command/peer.py
src/_repobee/hash.py
system_tests/gitea/test_reviews.py
tests/unit_tests/repobee/test_cli.py

#791 
Finalize `reviews end` for double-blind review by deleting the anonymous repos.

[feat] Delete anonymous repos on ending double-blind reviews

---

docs/install.rst
scripts/install.sh

[docs] Move tab completion instructions to docs

---

Dockerfile

[misc] Set UID/GID of repobee user in Docker to 1000

---

docs/docker.rst
docs/getting_started.rst
docs/install.rst
docs/userguide.rst

[docs] Document usage with Docker

---

Dockerfile
docs/docker.rst

[misc] Enable tab completion for bash in Docker image

---

Dockerfile

[misc] Remove RepoBee source directory in Docker image

---

docs/getting_started.rst
docs/gitea.rst
docs/userguide.rst

[docs] Document Gitea usage

---

docs/fundamentals.rst

Reduces the verbosity of the introduction and also includes some pointers to Gitea

[docs] Rewrite the overly verbose introduction

---

README.md

This PR completely overhauls the README. Verbosity is reduced, stuff is shuffled around to put the most appealing things at the top, and some new information is added about Gitea and Docker.

[docs] Give the README a much-needed update

---

src/_repobee/ext/gitea.py
system_tests/gitea/test_gitea.py

[fix] Raise NotFoundError in GiteaAPI.get_teams() when org does not exist

---

.github/workflows/tests.yml
requirements/app.txt
setup.py

[misc] Update python-gitlab to v2.6.0

---

src/_repobee/command/peer.py
src/_repobee/command/progresswrappers.py

There's no accompanying test, doesn't really seem worth the trouble of testing.

[fix] Fix progress bars in `reviews end`

---

src/_repobee/ext/gitea.py
system_tests/gitea/test_gitea.py

[fix] Fix crash in GiteaAPI api.get repos() when URL does not exist

---

docs/getting_started.rst
docs/gitea.rst
docs/index.rst

Adds some more details on how to use Gitea, in particular on how to use the demo instance.

[docs] Improve Gitea documentation

---

docs/getting_started.rst

[docs] Document how to create local config with `config wizard`

---

src/_repobee/ext/gitlab.py
system_tests/gitlab/_helpers/helpers.py
system_tests/gitlab/test_gitlab_system.py

Needed the full path, see issue https://github.com/repobee/repobee/issues/890

fix: Fix crash when using subgroup as target org

---

codecov.yml

Fix #897 
Adds a codecov.yml with comments disabled

[misc] Add codecov.yml with comments disabled

---

docs/repobee_plug/code.rst

[docs] Add the repobee_plug.config module to the docs

---

.flake8
requirements/test.txt
src/_repobee/cli/preparser.py
src/_repobee/command/peer.py
src/_repobee/git.py
src/_repobee/main.py
src/repobee_plug/serialize.py
tests/new_integration_tests/test_log.py
tests/unit_tests/repobee_plug/test_pluginmeta.py

[misc] Update to the latest version of Black

---

src/_repobee/disthelpers.py

Simple refactor of the `disthelpers.pip` function.

[fact] Refactor disthelpers.pip

---

setup.py

[misc] Upgrade MyPy to 0.902 and install type stubs

---

.github/workflows/tests.yml
src/_repobee/config.py
src/_repobee/constants.py
src/_repobee/ext/defaults/configwizard.py
src/repobee_plug/config.py
tests/new_integration_tests/test_config_category.py
tests/unit_tests/repobee/plugin_tests/test_configwizard.py
tests/unit_tests/repobee/test_config.py
tests/unit_tests/repobee_plug/test_plug_config.py

Fix #874 
This PR adds in support for config inheritance in the core application.

[feat] Add initial support for config inheritance in core application

---

src/_repobee/ext/defaults/merge_configurable_args.py

Simple refactor of a messy function.

[fact] Refactor merge_configurable_args module

---

src/_repobee/main.py

Complete refactoring of the entire main module. It was most convenient to do it all in one go as many of the functions are interdependent.
There's a slight behavioral change in the order of some error messages, but otherwise functionality remains precisely the same.

[fact] Refactor main module

---

.github/dependabot.yml

[misc] Add dependabot.yml

---

src/_repobee/cli/dispatch.py
src/_repobee/cli/mainparser.py
src/_repobee/cli/parsing.py

[fact] change to f-string in cli dir

---

src/_repobee/util.py

[fact] Replace format with f-string in util.py

---

src/_repobee/plugin.py

[fact] Replace format with f-string in plugin.py

---

src/_repobee/formatters.py

[fact] Replace format with f-strings in formatters.py

---

CONTRIBUTING.md

Just some minor updates to the CONTRIBUTING doc.

[docs] Update CONTRIBUTING.md

---

src/_repobee/ext/defaults/github.py

[fact] Use f-strings in GitHub module

---

tests/unit_tests/repobee/conftest.py
tests/unit_tests/repobee/constants.py
tests/unit_tests/repobee/functions.py
tests/unit_tests/repobee/plugin_tests/test_github.py
tests/unit_tests/repobee/plugin_tests/test_gitlab.py
tests/unit_tests/repobee/test_cli.py
tests/unit_tests/repobee/test_exception.py
tests/unit_tests/repobee_plug/test_deprecation.py

[fact] Run flynt on test code

---

src/repobee_testhelpers/localapi.py
tests/new_integration_tests/test_localapi.py

[test] Implement LocalAPI.for_organization

---

.github/workflows/tests.yml
setup.py
src/_repobee/colors.py
src/_repobee/command/issues.py
src/_repobee/formatters.py
tests/unit_tests/repobee/test_formatters.py

Something wrong with comparing outputs, they look identical to me and pass locally...

[fix] Define ANSI escape codes for coloring in RepoBee

---

requirements/test.txt

Pins the test requirements. There have been plenty of regressions in static analysis in the past years, so I want the upgrading of test requirements to be more controlled.

[misc] Pin test requirements

---

.github/workflows/tests.yml

Run scheduled tests on Saturdays instead of every day

[misc] Run scheduled tests on Saturdays

---

.github/workflows/tests.yml
.readthedocs.yml
README.md
docs/install.rst
scripts/install.sh
setup.py

[misc] Drop support for Python 3.6

---

.github/workflows/deploy.yml

gh workflow deploy.yml now uses Python v3.6

---

.github/workflows/tests.yml
README.md
scripts/install.sh
setup.py

[misc] add support for Python 3.10

---

.github/workflows/static-analysis.yml

[misc] Run pylint on tests in GHA workflow

---

.github/workflows/tests.yml

[misc] Run GitLab system tests on scheduled test runs

---

system_tests/gitlab/_helpers/asserts.py
system_tests/gitlab/test_gitlab_system.py

[test] Retry system test assertion to fix data race

---

src/_repobee/command/peer.py

#789 
Major refactoring of `peer.assign_peer_reviews`. The module is still in heavy need of refactoring, this is more or less just a first step.

[fact] Refactor peer.assign_peer_reviews

---

.github/dependabot.yml

Hope this makes dependabot find the requirements files

[misc] Set pip directory to /requirements

---

.github/workflows/deploy_dockerhub.yml

Fix #1027 
Adds a docker-deploy workflow that deploys `repobee/repobee:latest` on each push to master, and to stable releases on `release` events.

[misc] Add docker-deploy workflow

---

.github/workflows/deploy_dockerhub.yml

[misc] Checkout repository in docker-deploy workflow

---

.github/workflows/deploy_dockerhub.yml

[misc] Avoid running docker interactively

---

.pre-commit-config.yaml
src/_repobee/cli/mainparser.py
src/_repobee/cli/parsing.py
src/_repobee/constants.py
src/_repobee/ext/core_commands/repos.py
src/repobee_plug/config.py
src/repobee_testhelpers/funcs.py
tests/integration_tests/test_repos.py

Part 1/2 for #1038 
`--students` arg now accepts a filepath as an argument or configured value.

[feat] Make `--students` arg accept filepath and configurable

---

src/_repobee/ext/core_commands/repos.py
tests/integration_tests/test_repos.py

[fix] Make `--students` and `--students-file` mutually exclusive in plugin commands

---

src/_repobee/ext/core_commands/_options.py
src/_repobee/ext/core_commands/repos.py
src/_repobee/ext/core_commands/teams.py

[fact] Implement `teams create` as plugin

---

requirements/requirements.dev.txt
src/_repobee/disthelpers.py
src/_repobee/git/_util.py
src/_repobee/http.py

Composition of all of the dependabot dev dependency updates.

[misc] Update dev dependencies

---

setup.py
system_tests/gitlab/docker-compose.yml

#1085 
Both `python-gitlab` and the GitLab version used for the system tests were a bit out of date.

[misc] Update gitlab dependency and system test

---

scripts/install.sh
tests/integration_tests/test_dist.py

[fix] Fix bugs and inconsistencies in install script
