repobee/repobee

bin/repomate, repomate/cli.py, repomate/main.py, repomate/plugin.py, tests/test_cli.py, tests/test_main.py, tests/test_plugin.py
Adds `--p|--plug` option for specifying plugins to use (overrides defaults).
Adds `-np|--no-plugins` option for completely disabling plugins.
=> Plugin cli options

setup.py
The cause for `pluggy` not being the version required in `repomate-plug` was that it was also listed as a requirement in `setup.py` here in Repomate. Repomate should not require `pluggy`, it should let `repomate-plug` handle that.
Fix #133
=> Remove pluggy as a requirement in setup.py

repobee/command.py, repobee/github_api.py, tests/test_command.py, tests/test_github_api.py
Also refactors calling code to supply students+master repo names instead of student repo names.
Fix #179
=> [fact] Add students as optional argument to get_repo_urls

repobee/apimeta.py, repobee/exception.py, tests/test_apimeta.py
Adds a metaclass defining the platform (e.g. GitHub, GitLab) API behavior required by RepoBee. Should move over to `repobee-plug` once it's stable, so APIs can be implemented as plugins.
Fix #178
=> Add generalized API metaclass

docs/code.rst, repobee/apimeta.py, repobee/github_api.py, repobee/gitlab_api.py, tests/test_apimeta.py
APISpec methods properly documented, and API implementations (GitHubAPI and GitLabAPI) now just refer to the APISpec documentation.
Fix #191
=> Document apimeta.APISpec method stubs

repobee/apimeta.py, tests/test_apimeta.py
Fix #231 
This is possibly not the absolutely best solution, but it works fine and let's type checkers/autocompletion engines inspect the apimeta.API class and actually find the methods that are used in command.py and the tests. It also simplifies letting inheriting classes get the base implementations, as they simply inherit them. Works for now, at least!
=> [fact] Let API inherit from APISpec

tests/plugin_tests/test_defaults.py, tests/plugin_tests/test_pairwise.py, tests/test_cli.py, tests/test_github_api.py
This reverts commit 6d643bd78e9f3be1b0e28e135400bb01f09e9e89.
Fix #223
=> Revert "[misc] Temporarily don't call `all` in asserts (#224)"

repobee/cli.py, repobee/config.py, tests/test_cli.py
Order arguments such that the configurable ones and debug arguments (`--traceback`) come last, and non-configurable arguments (i.e. the ones that probably matter most for that command).
The configurable arguments are inherently ordered (maybe they should be), but the non-configurable ones aren't. In any case, this is a large improvement for consistency. Small caveat is that **non-public APIs are used in the argparse module, see the `_OrderedFormatter` class for details**
Fix #168
=> [feat] Order CLI arguments

docs/clone.rst, docs/configuration.rst, docs/getting_started.rst, docs/gitlab.rst, docs/peer.rst, tests/unit_tests/conftest.py, tests/unit_tests/constants.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_command.py, tests/unit_tests/test_config.py, tests/unit_tests/test_github_api.py, tests/unit_tests/test_main.py
A few base url-related names were left with the GitHub prefix in tests and docs. This pr removes the GitHub prefix.
=> [misc] Fix base url names

repobee/apimeta.py, tests/unit_tests/test_apimeta.py
This temporarily breaks CI.
Fix #275
=> [fact] Have apimeta only check subset of __init__ args

repobee/cli.py, tests/integration_tests/integration_tests.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_main.py
Most notably, when using the `gitlab` plugin, `user` no longer needs to be specified.
Fix #274
=> [feat] Make arguments not required by platform API optional

repobee/cli.py, repobee/main.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_main.py
Also introduces the `--show-all-opts` preparser option that unsuppresses any hidden options
Fix #164
=> [feat] Hide configured and optional args

repobee/apimeta.py, repobee/command.py, repobee/ext/github.py, repobee/ext/gitlab.py, repobee/util.py, tests/integration_tests/integration_tests.py, tests/unit_tests/test_command.py
Fix some issues related to the clone command. Most notably:
* `clone` now skips any repos that are already present in the current directory
* `clone` does not create local directories for repos which fail to be cloned
Also adds the `extract_repo_name` function to the APISpec, and implementations in `GitHubAPI` and `GitLabAPI`
It's mostly system tested. The old unit tests still run over the changed code but they don't test these specific aspects.
Fix #203
=> [fix] Fix problems with failed pulls and name conflicts

.travis/install.sh, src/_repobee/cli.py, src/_repobee/tuples.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_main.py
Fix #292 
Force-updating brew also seems to have solved the macOS problem, so fix #294
=> [fact] Replace use of tuples.Args with argparse.Namespace

src/_repobee/ext/configwizard.py, tests/unit_tests/plugin_tests/test_configwizard.py
If the config directory doesn't exist, config-wizard creates it with 700 permissions.
Fix #297
=> [fix] Make config-wizard create missing directories

requirements.txt, setup.py, src/_repobee/command.py, src/_repobee/ext/defaults.py, src/_repobee/ext/pairwise.py, src/_repobee/main.py, tests/unit_tests/plugin_tests/test_defaults.py, tests/unit_tests/plugin_tests/test_pairwise.py, tests/unit_tests/test_command.py
Refactor of the generate_review_allocations hooks. Pre-requisite for implementing reviews for teams with more than one member (see #167).
Fix #303
=> [fact] Refactor generate_review_allocations implementations

docs/gitlab.rst, docs/peer.rst, requirements.txt, setup.py, src/_repobee/cli.py, src/_repobee/ext/github.py
Fix #237 
Also puts the `purge-review-teams` as a deprecated parser
=> [feat] Rename purge-review-teams to end-reviews

requirements.txt, setup.py, src/_repobee/cli.py, src/_repobee/command.py, src/_repobee/formatters.py, src/_repobee/util.py, tests/unit_tests/test_cli.py
Add the `--hook-results-file` option to the clone command, to store hook results in JSON format in the specified file.
Fix #324 
Also works toward #153
=> [feat] Add --hook-results-file option to clone command

src/_repobee/cli.py, src/_repobee/main.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_main.py
Fix #362 
This conserves any information contained in the error message, which was previously lost in the context manager in the cli module.
=> [fact] Move SystemExit calls from cli module to main module

.travis.yml
=> Add Python 3.8 to Travis build matrix

src/_repobee/cli/dispatch.py, src/_repobee/cli/parsing.py, src/_repobee/command/repos.py, src/_repobee/git.py, src/_repobee/util.py, tests/integration_tests/integration_tests.py, tests/unit_tests/test_cli.py, tests/unit_tests/test_command.py
Redesign the clone command without affecting the CLI. This is a preparation for implementing `--discover-repos` and later `--discover-teams`. It should, ideally, not affect usage at all at this point.
Essentially, the change consists of changing `clone_repos(master_repo_names, students, api)` to `clone_repo(repos: List[plug.Repo], api: plug.API)`, and all other changes are just side effects of that.
Fix #404
=> Issue 404 redesign clone repos

requirements/app.txt, setup.py, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/ext/github.py, src/_repobee/ext/gitlab.py, tests/integration_tests/integration_tests.py, tests/unit_tests/test_cli.py
Fix #383 
Also:
* Bump version number for `repobee-plug` as a new API method was needed.
* Bump version number for `python-gitlab` as searching while including subgroups was required.
=> [feat] Implement `--discover-repos` for `clone` and `list-issues` commands

src/_repobee/main.py, src/_repobee/plugin.py, tests/unit_tests/repobee/test_main.py, tests/unit_tests/repobee/test_plugin.py
Fix #447 
Adds support for single-file plugins specified as filepaths. For example,  `repobee -p /home/slarse/exampleplug.py` tells RepoBee to load `/home/slarse/exampleplyg.py` as a plugin.
=> [feat] Add support for single-file plugins

docs/repobee_plug/creating_plugins.rst, src/_repobee/cli/dispatch.py, src/repobee_plug/_containers.py, tests/unit_tests/repobee/test_cli.py
Fix #480 
Extension command callbacks should now return `plug.Result` instead of `Mapping[str, List[plug.Result]]`
=> [break] Simplify extension command callback return value

src/_repobee/cli/mainparser.py, src/_repobee/cli/preparser.py, src/_repobee/ext/defaults/configwizard.py, src/_repobee/ext/javac.py, src/_repobee/plugin.py, src/repobee_plug/__init__.py, src/repobee_plug/_containers.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee/plugin_tests/test_configwizard.py, tests/unit_tests/repobee/test_main.py, tests/unit_tests/repobee/test_plugin.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
> This is potentially breaking, as it adds a required argument to the `repobee_plug.Plugin` constructor.
Fix #496 
Fix #490 
This PR implements declarative extension commands. Assume that we have a file called `command.py` with the following content.
```python
class ExtAction(plug.Plugin, plug.cli.Command):
__category__ = plug.CoreCommand.config
__action_name__ = "greeting"
__help__ = "The best extension action!"
__description__ = "The most impressive extension"
name = plug.cli.Option(
short_name="-n", help="Your name.", required=True, configurable=True
)
age = plug.cli.Option(
converter=int, help="Your age.", default=30, configurable=True
)
def command_callback(self, args, api):
print(f"Hello, my name is {args.name} and I am {args.age} years old")
```
This can …
=> [feat] Implement declarative extension commands

src/_repobee/cli/mainparser.py, src/repobee_plug/__init__.py, src/repobee_plug/_containers.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #493 
The implementation is a bit of a hack using the `ExtensionCommand` tuple in ways it's not intended to be used, and needs to be refactored, but it shows the primary functionality.
=> [feat] Allow plugin commands to add options to core parsers

src/_repobee/cli/dispatch.py, src/_repobee/main.py, src/_repobee/plugin.py, src/repobee.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #503 
This function is much more convenient to use for testing than the `main` function was.
This replaces the `main` function in the `repobee` module, but I'm not marking this as a breaking change as it is only breaking against the last alpha release.
=> [feat] Add run function to repobee module

bin/repobee, setup.py
Fix #506 
Using an entry point in `setup.py` makes setuptools generate the shell script instead.
=> [misc] Replace bin/repobee with entry point

src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #498 
Positional arguments can now be added with `repobee_plug.cli.Positional`. Here's an example:
```python
class Hello(plug.Plugin, plug.cli.Command):
name = plug.cli.Positional(help="Your name.")
age = plug.cli.Positional(converter=int, help="Your age.")
def command_callback(self, args, api):
print(f"Hello, my name is {args.name} and I am {args.age} years old")
```
```bash
$ repobee -p ext.py hello Todd 12
Hello, my name is Todd and I am 12 years old
```
Positionals appear on the command line in the order they are declared.
=> [feat] Add positional arguments to declarative plugin commands

src/repobee_plug/_containers.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #499 
Adds mutually exclusive groups to plugin commands. Can be used like so:
```python
class Hello(plug.Plugin, plug.cli.Command):
age_mutex = plug.cli.MutuallyExclusiveGroup(
age=plug.cli.Option(help="Your age.", converter=int),
half_age=plug.cli.Option(
help="Half your age.", converter=lambda half: int(half) * 2
),
__required__=True,
)
def command_callback(self, args, api):
print(f"Hello, my name is RALPH and I am {args.age if args.age else args.half_age} years old")
```
=> [feat] Add mutex groups to plugin commands

src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/ext/defaults/configwizard.py, src/repobee_plug/__init__.py, src/repobee_plug/_containers.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/integration_tests/conftest.py, tests/integration_tests/integration_tests.py, tests/unit_tests/repobee/test_cli.py, tests/unit_tests/repobee/test_main.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #502 
This adds two wrappers for command settings: `repobee_plug.cli.CommandSettings` (optional with `cli.Command`) and `repobee_plug.cli.CommandExtensionSettings` (required with `cli.CommandExtension`)
=> [feat] Wrap plugin command settings in object

src/_repobee/ext/defaults/configwizard.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #512 
The only difference from a usage perspective that this brings is that all of the CLI classes (except for `Command` and `CommandExtension`) have been made private, and are now constructed via functions. For example, what was previously `plug.cli.Positional` is now `plug.cli.positional`.
=> [fact] Refactor CLI plugin classes to be accessed via functions

src/_repobee/cli/mainparser.py, src/_repobee/main.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #500 
Plugins can now define categories of their own. It looks something like this:
```python
greeting = plug.cli.category(
name="greeting",
action_names=["hello"],
help="Make a greeting!",
description="Time to say hello :)",
)
class Hello(plug.Plugin, plug.cli.Command):
__settings__ = plug.cli.command_settings(
category=greeting,
help="Say hello!",
description="Say hello!",
)
name = option(required=True, help="your name")
def command(self, args, api):
print(f"Hello, {args.name}")
```
This can be called like so:
```bash
$ repobee -p ext.py greeting hello --name Simon
Hello, Simon
```
Note that the action name provided in the `plug.cli.category` must correspond with the action name of the command. Here, they match, as the class is called `Hello` (which in …
=> [feat] Allow plugin commands to add categories

src/_repobee/cli/dispatch.py, src/_repobee/ext/defaults/configwizard.py, src/_repobee/ext/javac.py, src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli/__init__.py, src/repobee_plug/cli/args.py, tests/unit_tests/repobee/test_cli.py, tests/unit_tests/repobee/test_main.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #525 
Previously, arguments were passed to callback functions via an `args` attribute. As it's inconvenient to try to pass this to all hook functions, arguments are now provided only through the `handle_parsed_args` and `handle_processed_args` hooks. `handle_processed_args` is now automatically implemented for plugin commands/extensions, and assigns arguments defined by the plugin to the destination in the instance.
The `command` function in a `plug.cli.Command` now does not take an `args` argument, instead arguments are accessed through `self`.
The entire namespace is assigned to `self.args`, such that command extensions can access all arguments, even the ones they did not define themselves.
Example:
```python
from repobee_plug.cli import (
option, …
```
=> [feat] Automatically assign parsed args to plugin command instances

src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli/__init__.py, src/repobee_plug/cli/args.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #531 
Example:
```python
class Flags(plug.Plugin, plug.cli.Command):
is_great = plug.cli.flag()
not_great = plug.cli.flag(const=False, default=True)
meaning = plug.cli.flag(const=42)
approve = plug.cli.flag(const="yes", default="no")
def command(self, api):
print("is_great", self.is_great)
print("not_great", self.not_great)
print("meaning", self.meaning)
print("approve", self.approve)
```
Can be called like so:
```bash
$ repobee -p ext.py flags --meaning --not-great
is_great False
not_great False
meaning 42
approve no
```
=> [feat] Add flag to plugin commands

requirements/app.txt, setup.py
=> [misc] Pin python-gitlab to v2.4.0

src/_repobee/ext/defaults/configwizard.py, src/repobee_plug/__init__.py, src/repobee_plug/_containers.py, src/repobee_plug/_exthooks.py, src/repobee_plug/_pluginmeta.py, tests/unit_tests/repobee/plugin_tests/test_configwizard.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #492 
A little quirk is that a plugin must be active in order to be configurable. I.e. to be able to configure the `junit4` plugin, you need to run `repobee -p junit4 config wizard`, or have it activated in some other way. Otherwise it won't appear.
=> [feat] Allow config wizard to configure plugins

src/_repobee/cli/parsing.py, src/_repobee/command/issues.py, src/_repobee/command/peer.py, src/_repobee/command/progresswrappers.py, src/_repobee/command/repos.py, src/_repobee/command/teams.py, src/_repobee/ext/defaults/genreviews.py, src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitlab.py, src/_repobee/ext/pairwise.py, src/repobee_plug/__init__.py, src/repobee_plug/_apimeta.py, src/repobee_plug/_containers.py, src/repobee_plug/_corehooks.py, src/repobee_plug/fileutils.py, src/repobee_plug/localreps.py, src/repobee_plug/testhelpers/localapi.py, tests/integration_tests/_helpers/const.py, tests/integration_tests/conftest.py, tests/integration_tests/integration_tests.py, tests/new_integration_tests/test_repos.py, tests/unit_tests/repobee/conftest.py, tests/unit_tests/repobee/constants.py, tests/unit_tests/repobee/plugin_tests/test_github.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py, tests/unit_tests/repobee/test_cli.py
Fix #567 
Uses `StudentTeam` and `StudentRepo` when an implementation is not available.
=> [fact] Use local representations of API objects when appropriate

docs/configuration.rst, docs/getting_started.rst, docs/gitlab.rst, docs/migrate.rst, src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/constants.py, src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitlab.py, src/repobee_plug/_containers.py, src/repobee_plug/platform.py, src/repobee_testhelpers/fixtures.py, src/repobee_testhelpers/funcs.py, src/repobee_testhelpers/localapi.py, tests/integration_tests/README.md, tests/integration_tests/_helpers/const.py, tests/integration_tests/_helpers/helpers.py, tests/integration_tests/conftest.py, tests/integration_tests/gitlabmanager.py, tests/integration_tests/integration_tests.py, tests/unit_tests/repobee/conftest.py, tests/unit_tests/repobee/constants.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py, tests/unit_tests/repobee/test_cli.py, tests/unit_tests/repobee/test_config.py
Fix #437 
This renames `master org name` to `template org name`
* The `--mo|--master-org-name` argument is now `--to|--template-org-name`
* The `master_org_name` config file key is now named `template_org_name`
=> [break] Rename "master org name" to "template org name"

.travis/upload_coverage.sh, src/_repobee/cli/mainparser.py, src/_repobee/ext/query.py, src/repobee_plug/_containers.py
Fix #582 
This PR also contains an entirely unrelated fix to the system test coverage uploading. I just had to get it in there.
* The `BaseParser.MASTER_ORG` parser is now called `BaseParser.TEMPLATE_ORG`
* The `BaseParser.REPO_NAMES` parser is now called `BaseParser.ASSIGNMENTS`
=> [break] Rename MASTER_ORG and REPO_NAMES base parsers

src/_repobee/command/repos.py, src/_repobee/plugin.py
Fix #593 
There's now a progress bar for post clone execution, and the results summary uses the repo names instead of the path names (which are just hashes nowadays).
=> [misc] Improve user feedback from post_clone hook execution

src/_repobee/command/issues.py, src/_repobee/command/progresswrappers.py, src/_repobee/command/repos.py, src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitlab.py, src/repobee_plug/platform.py, src/repobee_testhelpers/localapi.py
Fix #568 
Now, repo urls are used to unambiguously define the repositories, rather than using repo names.
This is breaking in regards to previous alpha releases, but not to any major release, so I won't mark it as breaking.
=> [fix] Make get_repos fetch by url instead of names

requirements/app.txt, scripts/install.sh, setup.py, src/_repobee/cli/parsing.py, src/_repobee/main.py
Fix #596 
Most of the magic happens in the install script. Currently, users have to add the completion themselves. This may change in the future.
I tried to get it working for fish, but it just wouldn't budge. I'll try again some other time.
=> [feat] Add tab completion for bash and zsh

src/_repobee/config.py, src/_repobee/constants.py, src/_repobee/main.py, tests/unit_tests/repobee/conftest.py, tests/unit_tests/repobee/test_config.py, tests/unit_tests/repobee/test_main.py
Fix #585 
* The `plugins` option in the config file is no longer available. Plugins should be configured in the installation.
=> [break] Remove plugins from config file

requirements/test.txt, scripts/install.sh, setup.py, src/_repobee/disthelpers.py, src/_repobee/ext/dist/pluginmanager.py, src/_repobee/main.py, system_tests/gitlabmanager.py, tests/new_integration_tests/test_dist.py
Fix #603 
The cause of the bug was that `capture_output` was used in calls to subprocess functions. And that argument was added in 3.7. Silly.
This PR also adds a test for the `plugin install` command, and a test file that makes it easy to test other dist plugins. It's rather slow-running as it depends on installing the distribution. This could possibly be sped up by not actually installing everything (because all that's needed is really the virtual environment and `installed_plugins.json`). But that's a topic for another day.
Oh, and the install script now accepts `REPOBEE_INSTALL_DIR` to be defined externally, and only defaults to `~/.repobee` if `REPOBEE_INSTALL_DIR` is not already defined.
=> [fix] Remove usage of capture_output in subprocess calls

src/_repobee/disthelpers.py, src/_repobee/ext/dist/distmanager.py, tests/new_integration_tests/test_dist.py
Fix #604 
Instead of adding a `--pre` flag, I just made it possible to install any version. It could potentially cause a user to break their install by specifying a too old version of RepoBee, but let's just happily assume that won't happen right now :D
The `manage upgrade` command also made use of the `capture_output` argument to `subprocess.run`, which isn't Python 3.6 compatible. So that's been fixed as well.
=> [feat] Add --version-spec option to `manage upgrade` command

src/_repobee/command/repos.py, tests/new_integration_tests/test_repos.py
Fix #621 
Adds a test for running `repos setup` with local repos and removes dead code that supposedly enabled that functionality. But it wasn't actually used.
=> [test] Test `repos setup` with local repos

src/_repobee/command/repos.py, src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitlab.py, src/repobee_plug/__init__.py, src/repobee_plug/exceptions.py, src/repobee_plug/platform.py, src/repobee_testhelpers/localapi.py, system_tests/test_gitlab_system.py, tests/unit_tests/repobee/plugin_tests/test_github.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py
Fix #626 
This also defines new behavior for the `insert_auth` function. Now, it must raise `plug.InvalidURL` if the URL provided does not belong to the target platform.
=> [fix] Fix crash on using local template repos

src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/main.py, system_tests/test_gitlab_system.py, tests/new_integration_tests/test_repos.py, tests/new_integration_tests/test_teams.py, tests/unit_tests/repobee/test_cli.py
Fix #627 
Adds the `--allow-local-templates` option to the `setup`, `update` and `migrate` commands. It currently doesn't make much sense for the migrate command as it's only function is to use local repos, but migrate should also be able to pull repos from the template organization.
If `--allow-local-templates` is not specified, and RepoBee finds local templates, an error is displayed listing the local templates and RepoBee exits.
=> [break] Add explicit option to allow use of local template repos

src/_repobee/command/repos.py, src/_repobee/git.py, tests/new_integration_tests/test_repos.py, tests/unit_tests/repobee/test_git.py
Fix #467 
The `setup`, `update` and `migrate` commands now use the default branch name of the template repo, instead of using "master".
There is a little quirk to this: cloned student repos will still always display Git's default branch name, which currently is "master". The reason for this is that student repos are "cloned" with a pull, and that simply feeds the default branch of the remote repo into the active branch of the local repo (which is always Git's default). 
This CAN be solved by first runing `git ls-remote --symref <REPO_URL>`, but that's an extra network call that I'd like to avoid.
=> [feat] Add support for default branch names other than master

src/_repobee/command/repos.py, src/repobee_testhelpers/funcs.py, tests/new_integration_tests/test_repos.py
Fix #630 
* `repos setup` does not try to push to existing repos anymore
* `repos update` does not create non-existing repos anymore
=> [fix] Fix repos setup/update semantics

README.md, docs/getting_started.rst, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/cli/preparser.py, src/_repobee/main.py, src/repobee_plug/_pluginmeta.py, tests/new_integration_tests/test_plugins.py, tests/unit_tests/repobee/test_cli.py, tests/unit_tests/repobee/test_main.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #634 
This turned out to cause massive issues in conjunction with plugins and tab completion. The only reasonable thing to do is to remove `--show-all-opts` and just show all options by default. It was after all just a dirty fix to a messy CLI. The CLI should be ordered in argument groups instead, for clarity.
Technically this is breaking and should lead to the release of RepoBee 4.0, but as RepoBee 3.0 has been out for just a few hours, I'm going to make an exception for this fix. It is after all a fix for a critical error.
=> [break] Remove the --show-all-opts functionality

docs/code.rst, src/_repobee/cli/argparse_ext.py, src/_repobee/cli/mainparser.py, tests/unit_tests/repobee/test_cli.py
Fix #638 
This update is purely cosmetic, there are no functional changes.
The CLI help sections are now much better organized and looks something like this:
```
$ repobee repos clone -h
usage: repobee repos clone [-h] [-u USER] [-o ORG_NAME] [--bu BASE_URL] [-t TOKEN] [--tb] (--sf STUDENTS_FILE | -s STUDENTS [STUDENTS ...]) (-a ASSIGNMENTS [ASSIGNMENTS ...] | --discover-repos) [--hook-results-file HOOK_RESULTS_FILE]
Clone student repos asynchronously in bulk.
optional arguments:
-h, --help            show this help message and exit
-s STUDENTS [STUDENTS ...], --students STUDENTS [STUDENTS ...]
One or more whitespace separated student usernames.
-a ASSIGNMENTS [ASSIGNMENTS ...], --assignments ASSIGNMENTS [ASSIGNMENTS ...]
one or more names of assignments
--discover-repos      discover all …
```
=> [misc] Group related CLI arguments

src/_repobee/cli/argparse_ext.py, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/git.py, src/_repobee/main.py, src/repobee_plug/cli/io.py, tests/new_integration_tests/test_repos.py
Fix #625 
The option stacks up to three times.
* `-q` silences stdout (so everything but warnings and errors)
* `-qq` also silences warnings
* `-qqq` also silences errors
A side note is that logging output that was previously on stdout now goes to stderr. It was actually supposed to go to stderr as of RepoBee 3 but I forgot about it. Additionally, the progress bars that previously went to stderr now go to stdout. I was not aware that they defaulted to stderr, and when they do silencing them requires separate handling, so they go to stdout instead. You're not meant to capture output from RepoBee commands anyway, that's what the logfile is for.
=> [feat] Add a `--quiet` option to silence stdout, warnings and errors

tests/new_integration_tests/conftest.py
=> [test] Force run_repobee to use temporary workdir in integration tests

setup.py, src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitlab.py, tests/unit_tests/repobee/plugin_tests/test_github.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py
Fix #665 
Also sneaks in the `typing-extensions` requirement into setup.py, as it was previously missing. Which caused issues.
=> [fix] Fix get_repos without argument in GitHub and GitLab APIs

src/_repobee/command/repos.py, src/_repobee/ext/tamanager.py, src/_repobee/git.py, src/_repobee/plugin.py, src/repobee_plug/_exthooks.py, src/repobee_testhelpers/localapi.py, tests/new_integration_tests/test_tamanager.py, tests/unit_tests/repobee/test_git.py
Fix #416 
This PR adds the `tamanager` plugin. It does three things:
* Adds the `add-teachers` command to the `teams` category.
- The command creates a `repobee-teachers` team, and adds the specified teachers to it
- All repositories in the organization are added with read access to `repobee-teachers`
- There is no `remove-teachers` command, as it's easier to just remove them manually from the `repobee-teachers` team.
* Adds a new hook, the `post_setup` hook, that is called on recently created student repositories
* Implements the `post_setup` hook such that any newly created student repositories are added to the `repobee-teachers` team.
=> [feat] Add plugin for managing teacher/TA read access

src/repobee_plug/__init__.py, src/repobee_plug/_corehooks.py, src/repobee_plug/_exthooks.py, src/repobee_plug/_pluginmeta.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #671 
This is a pure refactor. It simplifies things, as there is no longer need to register hooks from all of the different classes. It's enough to just register the modules.
=> [fact] Remove hook classes

src/_repobee/main.py, tests/unit_tests/repobee/test_main.py
Fix #666 
This is to let users deactivate or uninstall faulty plugins.
=> [misc] Make dist plugins load even when --no-plugins is specified

tests/new_integration_tests/test_dist.py
Fix #681 
The install script is now only executed once, and then the install dir is backed up locally. This speeds up execution significantly on my local machine, from ~100 seconds before to ~35 seconds after for the 10 dist tests. That's pretty massive.
=> [test] Use a backup of install dir in dist tests

src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
Fix #669 
See #669 for details on the functionality
=> [feat] Auto-truncate plugin tables to fit terminal width

src/_repobee/cli/dispatch.py
Fix #423 
Repobee should no longer shove an empty line in your face whenever a command returns a result.
=> [fix] Remove unnecessary INFO print after command

src/repobee_plug/__init__.py, src/repobee_plug/_corehooks.py, src/repobee_plug/hookmanager.py, src/repobee_plug/name.py, tests/new_integration_tests/test_repos.py
#694  
This PR adds the `generate_repo_name` hook, which when implemented overrides the `generate_repo_name` function in RepoBee plug.
Usage is very simple. For example, to replicate GitHub Classroom's naming scheme, all that's needed is a plugin like this:
```python
@plug.repobee_hook
def generate_repo_name(team_name, assignment_name):
return f"{assignment_name}-{team_name}"
```
Which can then for example be used like so with the `repos setup` command.
```bash
repobee -p ghclassroom.py repos setup ...
```
To fully fix the issue described in #694, we also need a GH Classroom plugin that implements the naming scheme outlined above.
=> [feat] Add hook to override generate_repo_name

src/_repobee/ext/ghclassroom.py, tests/new_integration_tests/test_plugins.py
Fix #714  
This PR adds a GitHub Classroom interoperability plugin. All it currently does is change the naming scheme in RepoBee from the default `<team_name>-<assignment_name>` to GitHub Classroom's `<assignment_name>-<team_name>`.
=> [feat] Add ghclassroom plugin

src/_repobee/plugin.py
Fix #419 
Only logs to log file, but it makes it easier to debug this stuff when a user reports an error.
=> [misc] Log ModuleNotFoundErrors when trying to load plugins

src/_repobee/exception.py, src/_repobee/git.py, tests/unit_tests/repobee/test_git.py
Fix #574 
This fixes the issue of all student repos initially being cloned to the same directory, which can case name collisions when using discovery mode. This is also necessary for #721 to work out properly.
=> [fix] Clone student repos to specified path

src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/command/repos.py, src/_repobee/git.py, src/repobee_testhelpers/funcs.py, tests/new_integration_tests/test_repos.py, tests/unit_tests/repobee/test_cli.py
Fix #693 
Adds the `--update-local` flag to the `repos clone` command, which allows local student repositories to be updated after having already been cloned.
=> [feat] Add --update-local flag to clone command

src/_repobee/ext/dist/distmanager.py
Fix #676 
Now prints the initial version and the version upgraded to on stdout.
=> [misc] Improve user feedback from `manage upgrade` command

src/_repobee/cli/parsing.py, src/_repobee/constants.py, tests/new_integration_tests/test_log.py
Fix #648 
Automatically limits the size of the logfile to 10 MiB. Whenever it exceeds that, (roughly) the first half is removed.
=> [misc] Limit size of logfile to 10 MiB

docs/_ext/generate_package_docs.py
Fix #730 
Adds labels on the form `.. _auto_<module_name>:` to the package doc generator, meaning that all builtin plugins can now be referenced. For example, the `tamanager` plugin can be referenced in documentation with `:ref:auto_tamanager`.
=> [docs] Add labels to builtin plugin docs

docs/README.md
There is now a `README.md` file in `docs/` linking to the documentation detailing how to build the documentation.
=> [docs] Add README detailing how to build documentation

src/_repobee/main.py, tests/new_integration_tests/test_plugins.py
Fix #744 
Instead of printing the "repobee exited unexpectedly" message on a plug error, print "A plugin exited with an error"
=> [misc] Print more specific error message on crash in plugin

src/_repobee/command/repos.py, src/_repobee/util.py, system_tests/test_gitlab_system.py, tests/new_integration_tests/test_repos.py
Fix #752 
This PR makes RepoBee crash early if there is a path clash between a non-Git directory and student repo that is about to be cloned
=> [fix] Crash early on path clash between non-Git directory and to-be-cloned student repo

src/repobee_testhelpers/fixtures.py, tests/new_integration_tests/test_dist.py, tests/new_integration_tests/test_plugins.py, tests/new_integration_tests/test_repos.py
There was a lot of repetition in creating a workdir for e.g. cloning repos, so this PR introduces a fixture in repobee_testhelpers called `workdir` that just does that.
=> [fact] Use tmp_path as workdir in integration tests

src/_repobee/ext/defaults/merge_configurable_args.py, tests/new_integration_tests/test_plugins.py
Fix #757 
Introduces a hookwrapper implementation of `get_configurable_args` that merges `ConfigurableArgs` instances that reference the same config section. Hookwrappers are really neat, [docs are here](https://pluggy.readthedocs.io/en/latest/#wrappers)
=> [fix] Merge configurable args for the same section to avoid duplication

Dockerfile
#735 
This is a draft for the Dockerfile for the public image of RepoBee. To use a config, one can mount a directory containing the config like so:
```bash
$ docker run --rm \
-v /path/to/dir/with/config:/home/repobee/.config/repobee/ \
-t repobee:latest \
repobee config show
```
My currently best idea for making the install directory persistent (to allow for using plugins) is something like this.
```bash
$ docker run --rm -v install_dir:/home/repobee/install_dir \
-t repobee:latest \
cp -r /home/repobee/.repobee/* /home/repobee/install_dir
$ docker run --rm -v install_dir:/home/repobee/.repobee \
-it repobee:latest \
repobee plugin install
```
It's a bit awkward, but it seems to work.
=> [misc] Add Dockerfile for public image

docs/faq.rst, src/_repobee/cli/mainparser.py, tests/new_integration_tests/test_config_category.py
Fix #763 
This PR simply makes `config verify` check that the students file exist (indirectly by failing to parse it, really), and a new entry in the FAQ on how to deal with the general "'blabla' is not a file" error message.
=> [feat] Make `config verify` check that `--students-file` exists

src/_repobee/command/repos.py, src/_repobee/plugin.py, src/repobee_plug/_exthooks.py, tests/new_integration_tests/test_repos.py
Related to discussion in #769 
This PR appends allows the `post_setup` hook to process both newly created and existing student repos, whereas previously it would only be passed newly created ones. A new parameter `newly_created` is appended to the hook function's parameter list to indicated whether or not the passed in repository already existed or was newly created. Existing hook functions will therefore keep working, unless they rely on only being passed newly created repositories.
**This update is still breaking**, as any hook implementation that relied upon the passed repository being newly created will no longer be able to do so.
=> [break] Allow post_setup to process both newly created and existing repos

src/_repobee/ext/gitlab.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py
Fix #774 
This PR fixes a paging issue when fetching groups of specific names in GitLab. Previously the search API was used, only fetching the first page. With this patch, the group name is used to fetch the group directly, instead.
=> fix: Fix paging error in fetching GitLab group

docs/repos.rst
I'm a brand new RepoBee user, so this may in fact be my error and I'd love to learn from the experience.
When I tried to follow these directions to migrate a local template repository into an organization --- which I think is the expected use case --- I got an error from RepoBee indicating that this wasn't allowed without the --allow-local-templates option. I see that this was added recently in repobee#629, and so perhaps updating this documentation page was overlooked.
=> Add allow-local-templates to migrate documentation

src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
This PR addresses part 1/3 of #782: non-interactive plugin installation. This is important for using RepoBee in scripts, for example when using the Docker distribution. With this, one can install for example `junit4` `v1.0.0` like so:
```
$ repobee plugin install --plugin-spec junit4@v1.0.0
```
The reason it's collapsed into a `--plugin-spec` instead of separate `--plugin-name` and `--plugin-version` is that it's enormously much easier to make `--plugin-spec` mutually exclusive to `--local` (and later `--remote`, when that's implemented), than it is to make `--plugin-name` AND `--plugin-version` mutually exclusive to `--local`, but dependent on each other.
=> [feat] Add non-interactive plugin installation

CODE_OF_CONDUCT.md
Add the [contributor covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) code of conduct
=> [docs] Add code of conduct

src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
Part 2/3 of #782 
This PR adds a non-interactive mode to `plugin uninstall` with the `--plugin-name` argument. A plugin can be non-interactively installed like so:
```
$ repobee plugin uninstall --plugin-name junit4
```
=> [feat] Add non-interactive plugin uninstall

src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
Part 3/3 of #782. Adds a non-interactive mode to `plugin activate`, where running the following toggles the active-status of a single plugin.
```bash
$ repobee plugin activate --plugin-name junit4
```
=> [feat] Add non-interactive mode to `plugin activate`

system_tests/gitea/test_gitea.py
#732
Adds a test for the previously untested (but implemented) `assign_repo` function.
=> [test] Add test for assign_repo

src/_repobee/ext/gitea.py, system_tests/gitea/test_gitea.py
#732 
This PR adds `close_issue` to the `GiteaAPI`. Also fixes a bug in `get_repo_issues` that caused closed issues not to be fetched, which was needed to test the new function.
=> [feat] Implement GiteaAPI.close_issue

src/_repobee/ext/gitea.py, system_tests/gitea/test_gitea.py
Makes `GiteaAPI.create_issue` actually assign assignees to issues. Previously, it simply ignored the assignees argument.
=> [fix] Actually assign assignees to issues on Gitea

src/_repobee/ext/gitea.py, system_tests/gitea/test_gitea.py
Fixes a bug in that the `team` argument to `GiteaAPI.create_team` was silently ignored
=> [fix] Actually assign repository to specified team in GiteaAPI.create_repo

src/_repobee/command/peer.py, system_tests/gitea/conftest.py, system_tests/gitea/test_gitea.py, system_tests/gitea/test_reviews.py
Related to #802 
Assigning reviewers to the review issue on Gitea isn't possible, as Gitea prohibits users with read-access only to be assignees. This PR makes it such that RepoBee does not try to assign reviewers as assignees if Gitea is used. It's a temporary solution, the review assignment is to be redesigned.
=> fix: Don't assign reviewers as assignees for Gitea

requirements/app.txt, setup.py
Changes a misspelling of a dependency, which just happened to be an actual package that depended on the desired dependency. The package is not malicious, so it isn't a security risk, but it should still be removed ASAP.
=> [misc] Correct GitPython dependency

src/_repobee/cli/dispatch.py, src/_repobee/command/peer.py, system_tests/gitea/test_reviews.py
Fix #791 
Final piece of the puzzle to support double-blind reviews. Well, except actually distributing the reviews to the affected students.
=> [feat] Add support for double-blind in `reviews check`

src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/command/issues.py, tests/new_integration_tests/test_issues.py
This PR makes it possible to list issues from anonymous repos (created in double-blind peer review assignment) with the `issues list` command by supplying the `--double-blind-key` option.
=> [feat] Support double-blind repos in `issues list`

src/_repobee/command/peer.py, tests/new_integration_tests/test_reviews.py
Fix #815 
Double-blind peer review would previously create anonymous repo copies for all student repos. That's not great :D.
=> [fix] Only create anonymous repo copies for reviewed repos

src/_repobee/cli/argparse_ext.py, src/_repobee/cli/mainparser.py
#811
Makes the `--double-blind-key` argument appear in the "Alpha arguments" section of the help listing.
=> [feat] Include --double-blind-key in alpha arguments

src/_repobee/command/issues.py, src/_repobee/command/peer.py, system_tests/gitea/test_reviews.py, tests/new_integration_tests/test_issues.py
#811 
`issues list` with `--double-blind-keys` now shows the original repo names instead of the names of the anonymous copies. This is semi-confusing, but we'll add a message in the future to highlight that these are de-anonymized names.
=> [feat] Make `issues list` on anonymous repos show original repo names

src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/command/__init__.py, src/_repobee/command/issues.py, src/repobee_plug/serialize.py, tests/new_integration_tests/test_issues.py
Fix #811 
Makes it possible to distribute double-blind reviews through two extensions.
1. Add more data to the output from `issues list`, experimental format.
2. Make it possible to open issues from a hook results file using the new experimental format with `issues open --hook-reusults-file hf.json`.
It's a bit janky, but it should work as a first prototype.
=> [feat] Add functionality to distribute double-blind reviews

src/_repobee/ext/defaults/github.py, tests/unit_tests/repobee/plugin_tests/test_github.py
Fixes a bug that causes GitHubAPI.insert_auth to use the URL to the organization instead of the provided URL. Silly.
=> [fix] Fix GitHubAPI.insert_auth using the wrong URL

docs/getting_started.rst, src/_repobee/cli/preparser.py, src/_repobee/constants.py, src/_repobee/main.py, tests/new_integration_tests/test_config_category.py
Fix #465 
This PRs adds support for "local" configuration files. If you place a config file called `repobee.ini` into the current working directory, it overrides the global config file.
=> [feat] Add support for local configuration files

src/_repobee/config.py, src/_repobee/ext/defaults/configwizard.py, src/repobee_plug/_exthooks.py, tests/new_integration_tests/test_config_category.py
Fix #824 
This PR adds the `handle_config` hook, which uses the new Config wrapper. It replaces the `config_hook`, which is now deprecated and is to be removed by 3.8.0.
As a proof of concept, the config wizard uses the new hook, which is what fixes #824.
=> [feat] Add handle_config hook

src/_repobee/command/peer.py, tests/new_integration_tests/test_reviews.py
Fix #825
Makes it such that the deletion of anonymous repos does not depend on the review teams still existing.
=> [fix] Make deletion of anonymous repos not depend on teams

.github/workflows/tests.yml, src/_repobee/ext/gitlab.py, system_tests/gitlab/test_gitlab_system.py
Fix #812 
The token owner should not be assigned as a member of a group in GitLab as it is by default part of any group it creates.
=> [fix] Avoid assigning token owner as member of GitLab group

src/_repobee/disthelpers.py, tests/new_integration_tests/test_dist.py
Fix #848 
This PR replaces the use of `--use-feature=2020-resolver` with an auto-update of `pip` on each install. This is because the latest version of `pip` has the resolver enabled by default, and `--use-feature=2020-resolver` will soon cause errors for users (it already causes test failures).
=> [fix] Replace --use-feature=2020-resolver with pip auto-update

src/_repobee/ext/defaults/configwizard.py, src/repobee_plug/config.py, tests/new_integration_tests/test_config_category.py
Fix #863 
No prints the path to the config file that's actually used, rather than always printing the path to the default file.
=> [fix] Print path to actual storage location of config file in `config wizard`

docs/contributing.rst
I'm starting off getting the development environment installed, and found the pipenv install command didn't work with zsh (my default shell). Putting quotes around ".[TEST]" works for both zsh and bash, so it seemed like adding this might make sense.
I also fixed an exceedingly minor typo while I was at it.
=> Added quotes to pipenv install to enable working on zsh

docs/getting_started.rst, src/_repobee/main.py, tests/new_integration_tests/test_config_category.py
Fix #873 
PR introduces config file lookup up the directory tree, as opposed to only looking in the current directory.
=> [feat] Lookup config file up the directory tree

docs/plugins.rst, src/_repobee/disthelpers.py, src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
Fix #865 
This PR makes it possible to install a plugin from a remote Git repository. Usage like so:
```
$ repobee plugin install --git-url https://github.com/repobee/repobee-junit4.git
$ repobee plugin install --git-url https://github.com/repobee/repobee-junit4.git@v1.0.0
```
The version specifier (here, `v1.0.0`) can be any Git ref.
=> feat: Add option to install plugins from Git URL

src/_repobee/config.py, tests/unit_tests/repobee/test_config.py
#460
Rewrites all instances of `str.format` in the config module (and its unit test file) to use f-strings instead.
=> [fact] Rewrite str.format to f-strings in config module

src/_repobee/ext/defaults/configwizard.py, tests/new_integration_tests/test_config_category.py
Closes #870
This fixes the output for `repobee config wizard` so that it will use the actual config file path in the initial print of the file that will be overwritten, instead of the constant value.
=> [fix] Print actual config file path in wizard

tests/new_integration_tests/test_config_category.py
Per comment in #883, splitting this test change into its own PR. This change narrows the assert so that the string has to appear at the end of the output, rather than anywhere within the input.
=> [test] improve config wizard test assert

src/_repobee/exception.py, tests/unit_tests/repobee/test_exception.py
Work for #460
This updates the exception module to now use f-strings instead of str.format where possible. There were a few instances of str.format left in the test module as it does:
```python
repo_url_template = "https://{}some-host.com/some-repo"
repo_url = repo_url_template.format("")
repo_url_with_token = repo_url_template.format(token + "@")
```
which is a proper use-case for str.format over f-strings.
=> [fact] Rewrite str.format to f-strings in exception module

.github/workflows/tests.yml
Fix #892 
This PR makes it possible to run GitLab system tests on pull requests by adding the `gitlab` label to the PR (and then e.g. close and reopen, or push anything). This makes it easy for a maintainer to trigger the system tests, but avoids abuse from others as you need issue triage rights to set labels.
=> [misc] Trigger GitLab system tests with label on PR

src/_repobee/git.py, tests/unit_tests/repobee/test_git.py
Continued work for #460.
This replaces all usages of str.format with f-strings where possible in the git.py module and its related unit test file.
=> [fact] Rewrite str.format to f-strings in git module

src/_repobee/ext/gitlab.py, system_tests/gitlab/_helpers/const.py, system_tests/gitlab/gitlabmanager.py, system_tests/gitlab/test_gitlab_system.py
Fix #896 
The whole issue is thoroughly detailed in #896. This PR fixes the problem by unconditionally setting branch protection to none (0) for groups created with the GitLabAPI class.
=> [fix](gitlab) Disable student group branch protection

docs/getting_started.rst
I found this the hard way, and thought it might be useful to save others the effort. If one is using GitHub Actions, such as for autotesting, it doesn't get enabled in the student repos unless the `workflow` scope is enabled.
=> [docs] add workflow scope if using GitHub Actions

src/repobee_plug/localreps.py, src/repobee_plug/platform.py, system_tests/gitlab/test_gitlab_system.py, tests/unit_tests/repobee_plug/test_localreps.py, tests/unit_tests/repobee_plug/test_platform.py
Fix #900 
This PR fixes a problem where student usernames were treated case sensitively, while all of the supported platforms are case insensitive. The fix is simply that `StudentTeam` and `Team` both automatically lowercase the names of all members.
* `StudentTeam` lowercasing names ensures that user input is lowercase (as all student usernames provided by the user are wrapped in this class)
* `Team` ensures that usernames fetched from the platform are lowercase
This however does not guard against plugins using the `PlatformAPI` directly, and additional work is needed to safeguard there. But that can wait for another time.
=> [fix] Automatically lowercase all usernames

src/_repobee/ext/defaults/github.py, src/_repobee/ext/gitea.py, src/_repobee/ext/gitlab.py, src/repobee_plug/platform.py, system_tests/gitea/test_gitea.py, tests/unit_tests/repobee/plugin_tests/test_github.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py
Fix #882 
This PR adds the `for_organization(org_name: str) -> PlatformAPI` function to the platform API specification. It returns a copy of the API it's called on, but targeting the provided organization instead. The PR also adds implementations for all three API implementations (GitLab, Gitea, GitHub).
=> [feat] Add PlatformAPI.for_organization and implementations

requirements/docs.txt, setup.py
#906 
Due to problems with Sphinx 4.0.0, we use 3.5.4 for the time being.
=> [docs] Require Sphinx version 3.1.1 to 3.5.4

requirements/docs.txt, setup.py
Fix #906 
The bug causing doc build failures was swiftly fixed by the Sphinx maintainer.
=> [misc] Set Sphinx version number >=4.0.1

README.md
Fix #396 
I just discovered that GitHub now supports embedding MP4 videos into READMEs. This PR embeds a RepoBee demo video at the top of the README.
Note that a little hack is used here: I uploaded the video in an issue (#923), which makes it user content. File size is 10 MB, so the quality is pretty poor, but it's something!
@monperrus it only took a year and a half to fulfill your request :). But this is much better than just a GIF.
=> [docs] Add demo video to README

src/repobee_plug/config.py, tests/new_integration_tests/test_config_category.py
Fix #920 
With this PR, relative parent paths are resolved relative to the config file in which they are written. Absolute parent paths are still allowed and are used as-is.
=> [feat] Resolve parent path relative to config file path

src/_repobee/constants.py, src/repobee_plug/config.py, tests/new_integration_tests/test_config_category.py, tests/unit_tests/repobee_plug/test_plug_config.py
Fix #925 
This PR renames the parent config key from "parent" to "parent_config" to make it more clear what it relates to, and puts the precise name into a constant such that changing it is less of a hassle.
=> [fact] Rename parent config key to "parent_config" and store in constant

src/repobee_plug/types.py
Pyling is giving some false positives on a protocol, this PR just ignores the warnings.
=> [misc] Ignore pylint false positives on protocol

src/_repobee/cli/dispatch.py, src/_repobee/cli/mainparser.py, src/_repobee/command/repos.py, src/_repobee/fileutil.py, tests/new_integration_tests/test_repos.py, tests/unit_tests/repobee/test_cli.py
Fix #881 
This PR introduces the `--dl|--directory-layout`, which allows a user to choose how repositories the layout into which repositories are cloned.
Currently, there are only two options: `by-team` and `flat`
* `by-team`: This is the default, where the repositories of each team are placed in a subdirectory with the name of the team
* `flat`: This is a new layout in which each repository is cloned into the current working directory, without organizing into subdirectories
I also plan to add a `by-task` layout, which is something that I've personally wanted to have for quite some time.
@davbeek Any thoughts?
@tohanss ping for review
=> [feat] Add `--directory-layout` option to choose layout of cloned repositories

.pre-commit-config.yaml, src/_repobee/command/repos.py, src/_repobee/ext/squash.py, src/_repobee/plugin.py, src/repobee_plug/_exthooks.py, tests/new_integration_tests/test_repos.py
Fix #899 
This PR adds a `squash` plugin that causes template repos to be squashed before being pushed to students. It's an implementation of the `pre_setup` hook that has been modified to allow for persisting changes by committing. To use the plugin, simply activate it and run `repos setup` as usual, optionally providing the `--squash-message` option to decide the message of the squash commit.
=> [feat] Add squash plugin for squashing template repos

src/_repobee/cli/parsing.py, src/_repobee/ext/defaults/students_file_parser.py, src/repobee_plug/_corehooks.py
#880 
This PR is part refactor, part feature. It extracts the parsing of the students file into a hook function such that the exact implementation can be overridden with plugins. This opens up for implementing students file parsing in any way one wishes to.
@davbeek I've briefly played around with this to implement a plugin for to parse YAML files, allowing one to specify something like this:
```yml
some-team:
members: [alice, eve, bob]
other-team:
members: [simon, ric]
```
This would create the teams `some-team` and `other-team` with the specified members, and any associated repos would by default then have names prefixed with those team names (as usual). You could of course add that group id of yours as part of the team name. I haven't decided on the details here, but the good news is …
=> [feat] Extract parsing of students file into a hook function

src/repobee_testhelpers/localapi.py, tests/new_integration_tests/test_repos.py, tests/new_integration_tests/test_reviews.py
Fix #936 
This PR makes LocalAPI only store the platform state (i.e. the repos, teams and users), and not the connection settings to the platform (i.e. user, token etc) in the pickle file. This solves the problem of it being impossible to create a new API with a different value in the connection settings, such as a different user, as that was always immediately overwritten when restoring the state in the constructor.
There's still a problem with synchronization: if multiple instances of LocalAPI are used concurrently, they'll overwrite each others' states, as the state is only ever restored when the instance is created. But that's for a separate issue.
=> [fix] Fix LocalAPI overwriting connection settings

src/repobee_plug/platform.py
=> [docs] Fix typo in _APISpec docstring

setup.py, src/_repobee/ext/studentsyml.py, src/repobee_testhelpers/funcs.py, tests/new_integration_tests/test_repos.py, tests/new_integration_tests/test_teams.py, tests/unit_tests/repobee/plugin_tests/test_studentsyml.py
Fix #880 
This PR adds a plugin, `studentsyml`, that supports an extended students file syntax based on YAML.
The happy-path behavior is seemingly working fine, but error-handling needs to be implemented.
=> [feat] Add extended students file syntax based on YAML

scripts/install.sh, tests/new_integration_tests/test_dist.py
Fix #960 
Alter the install script to clobber the `installed_plugins.json` file on reinstall. This can repair an install that is broken due to a broken plugin, and prevents breaking an install by breaking a plugin with an update.
=> [fix] Clobber installed_plugins.json on reinstall

src/_repobee/ext/dist/pluginmanager.py, tests/new_integration_tests/test_dist.py
fix #768 
This PR improves the error message printed when installing a plugin that's incompatible with the current version of RepoBee. It prompts the user to upgrade RepoBee and try again, relying on the fact that most plugins specify requirements on the form `repobee>=x.y.z`.
=> [misc] Improve error message on trying to install incompatible plugin

src/_repobee/command/repos.py, src/repobee_testhelpers/localapi.py, tests/new_integration_tests/test_repos.py
Fix #771 
The StudentTeam names were derived from the actual members of the team, which didn't work when the students didn't yet exist.
=> [fix] Fix empty StudentTeam name in post_setup hook

src/_repobee/cli/dispatch.py
Pure refactoring of the `dispatch` module to improve readability.
=> [fact] Refactor the dispatch module

src/_repobee/git/_fetch.py, src/_repobee/git/_util.py
The check was case sensitive, and the version of Git running in GitHub Actions used all lowercase (which RepoBee did not account for). See #981
=> [fix] Make empty repo check non-case sensitive

src/_repobee/ext/gitlab.py, tests/unit_tests/repobee/plugin_tests/test_gitlab.py
Fetching e.g. `OWNER_ACCESS` on the `gitlab` module is deprecated, should be accessed through `gitlab.const` now.
=> [fix] Fetch access rights through gitlab `const` object

docs/gitlab.rst
=> [docs] Document that root group in GitLab must allow project sharing

setup.py, src/_repobee/ext/defaults/github.py, src/_repobee/rate_limit.py, tests/unit_tests/repobee/test_rate_limit.py
Fix #991 
With background of #991  and the new secondary rate limits in the GitHub API, we need to rate limit modify requests to 1 per second. This will significantly slow down certain portions of using RepoBee, but stability is more important than speed.
This may also be necessary to investigate for GitLab and Gitea, but I won't travel that road until a problem is reported (as of yet, nothing).
=> [fix] Rate limit modify requests in GitHub API

src/_repobee/ext/core_commands/repos.py
#998 
Implementation of `repos setup` as a plugin. Can be enabled with the `REPOBEE_CORE_COMMANDS_AS_PLUGINS` flag set to `true`.
=> [feat] Implement `repos setup` as a plugin

src/repobee_plug/platform.py, tests/unit_tests/repobee_plug/test_platform.py
Fix #1014, #900 
This PR lowers authors' usernames to match the case-insensitive style used throughout the project. 
- Fixes a case where checking reviews compared issue authors' "real" GitHub usernames (not lowercased) with the internally saved team usernames, which have already received the lowercase treatment. The `reviews check` command would as a consequence not correctly mark finished reviews as such.
=> [fix] lowercase issue author usernames

Dockerfile
The latest version of `PyGithub` apparently had dependencies needing to be compiled with `gcc`. Took the opportunity to clean up the image a bit.
=> [misc] Update Dockerfile to actually work

.github/workflows/tests.yml
Codecov is failing sporadically which is super annoying. The whole build should continue even if Codecov upload fails.
=> [misc] Avoid failing build if codecov upload fails

src/repobee_plug/_pluginmeta.py, src/repobee_plug/cli/args.py, tests/new_integration_tests/test_plugins.py, tests/unit_tests/repobee_plug/cli/test_args.py, tests/unit_tests/repobee_plug/test_pluginmeta.py
Fix #1035 
Adds support for mutually exclusive groups to have a single configurable argument. More than one configurable argument is an error.
Mutex groups can be conditionally required. This means that a mutex group with `__required__=True` AND a configurable argument becomes non-required if said argument is configured.
=> [feat] Add support for a single configurable argument in mutex groups

.pre-commit-config.yaml, src/_repobee/cli/mainparser.py, src/_repobee/cli/parsing.py, src/_repobee/constants.py, src/_repobee/ext/core_commands/repos.py, src/repobee_plug/config.py, src/repobee_testhelpers/funcs.py, tests/integration_tests/test_repos.py
Reverts repobee/repobee#1040
The usage of `--students` with two completely different kinds of input (a single filepath or any amount of student usernames) is just too confusing, I think.
=> Revert "[feat] Make `--students` arg accept filepath and configurable"

.pylintrc, src/_repobee/cli/argparse_ext.py, src/_repobee/main.py, tests/integration_tests/test_repos.py
Add a `--verbose|-v` debug flag that stacks up to two times for INFO and DEBUG logging.
=> [feat] Add verbose output mode

tests/integration_tests/test_dist.py
#1116 Installing RepoBee versions 3.x before 3.8.1 doesn't work if you install from source as the version specifier for `dataclasses` is broken. This test was failing as it used an old beta version.
=> [test] Fix broken dist test

scripts/install.sh
First install must not be from a wheel because then it won't enable the `plugin` and `manage` commands. See the shenanigans in `setup.py` and `distinfo.py`.
Fix #1144
=> [misc] Make install script install from GitHub instead of PyPi

requirements/requirements.dev.txt, setup.py
It hasn't been used in a long time as we use the Codecov GitHub Action and [it was recently (apparently accidentally) removed from PyPi](https://about.codecov.io/blog/message-regarding-the-pypi-package/).
=> Remove codecov dependency

system_tests/gitea/giteamanager.py, system_tests/gitlab/gitlabmanager.py
Fix #1267 
Fix #1268 
The `docker-compose` command was deprecated a while back, so it might just be that the runner image was updated to only have the newer `docker compose` sub command.
=> [test] try running docker compose instead of docker-compose

.github/workflows/tests.yml, README.md, scripts/install.sh, setup.py, tests/integration_tests/test_dist.py
Fix #1205
Python 3.12 seems fine, but Python 3.13 seems to be causing issues in the integration (distro) tests on macOS.
=> [misc] Add support for Python 3.12 and 3.13
